version = 0.1

[default.deploy.parameters]
stack_name = "sam-backend-demo"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true
disable_rollback = false
resolve_s3 = true
