AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Simple SAM backend

Parameters:

  TableName:
    Type: String
    Default: sam-messages-table

Resources:

  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S

      KeySchema:
        - AttributeName: id
          KeyType: HASH
  
  MessagesDLQ:
    Type: AWS::SQS::Queue

  MessagesQueue:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt MessagesDLQ.Arn
        maxReceiveCount: 3

  ObservabilityStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: templates/observability.yaml
      Parameters:
        MessagesDLQName: !GetAtt MessagesDLQ.QueueName
  
  CreateMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: create_message.lambda_handler
      Runtime: python3.12
      CodeUri: src/

      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
          QUEUE_URL: !Ref MessagesQueue
      
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt MessagesQueue.QueueName

      Events:
        MessageApi:
          Type: Api
          Properties:
            Path: /message
            Method: post

  ProcessMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: process_message.lambda_handler
      Runtime: python3.12
      CodeUri: src/

      Environment:
        Variables:
          TABLE_NAME: !Ref TableName

      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref TableName

      Events:
        MessagesQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MessagesQueue.Arn
            BatchSize: 10

  GetMessagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get_messages.lambda_handler
      Runtime: python3.12
      CodeUri: src/

      Environment:
        Variables:
          TABLE_NAME: !Ref TableName

      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TableName

      Events:
        GetMessagesApi:
          Type: Api
          Properties:
            Path: /messages
            Method: get

  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello.lambda_handler
      Runtime: python3.12
      CodeUri: src/

      Events:
        HelloApi:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Outputs:
  ApiBaseUrl:
    Description: Base URL for the deployed API
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

  MessagesTableName:
    Description: DynamoDB table name
    Value: !Ref MessagesTable
