AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Simple SAM backend

Resources:

  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: sam-messages-table
      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S

      KeySchema:
        - AttributeName: id
          KeyType: HASH

  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello.lambda_handler
      Runtime: python3.12
      CodeUri: src/

      Policies:
        - DynamoDBCrudPolicy:
            TableName: sam-messages-table

      Events:

        HelloApi:
          Type: Api
          Properties:
            Path: /hello
            Method: get

        MessageApi:
          Type: Api
          Properties:
            Path: /message
            Method: post

        GetMessagesApi:
          Type: Api
          Properties:
            Path: /messages
            Method: get
