name: Deploy SAM Backend Prod

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-prod:
    uses: ./.github/workflows/reusable-sam-deploy.yml
    with:
      stack-name: sam-backend-prod
      environment-name: prod
      table-name: sam-messages-table-prod
      api-url: https://np8s8oehmd.execute-api.us-east-1.amazonaws.com/Prod
