name: Deploy SAM Backend Dev

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "infrastructure/sam-backend/**"

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    uses: ./.github/workflows/reusable-sam-deploy.yml
    with:
      stack-name: sam-backend-dev
      environment-name: dev
      table-name: sam-messages-table-dev
      api-url: https://ekufigu896.execute-api.us-east-1.amazonaws.com/Prod
